name: mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  audioplayers: ^6.5.1
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  glassmorphism: ^3.0.0
  google_fonts: ^6.3.3
  http: ^1.6.0
  intl: ^0.20.2
  lottie: ^3.3.2
  pdf: ^3.10.4
  printing: ^5.11.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  flutter_local_notifications: ^18.0.1
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/
